////////////////////////////////////////////////////////////////////////////////
/////                          Project: MetaDat                          ///////
////////////////////////////////////////////////////////////////////////////////
////                                                                        ////
////                    Author: Zergham Warraich                            ////
////                    Date:   Friday, 22 July, 2022                       ////
////                    Git Initialized:   Sat 23, July, 2022               ////
////                                                                        ////
////                                                                        ////
////////////////////////////////////////////////////////////////////////////////

import tw from "tailwind-styled-components"  // Importing tailwind-styled-components
import mapboxgl from '!mapbox-gl'  // Importing mapbox-gl
import { useEffect } from 'react'  // Importing useEffect

mapboxgl.accessToken = 'pk.eyJ1IjoiemVyZ2hhbXdhcnJhaWNoIiwiYSI6ImNsNXdlcWN4ZjAwaTIzaW1tdms4andiNDQifQ.uLI65gh6lFYJNf4apvvJDA' // This is accesstoken generated by MapBox API upon Account Creation... Please Use your own for flexible functionlity of this API...

const Map = (props) => { //props are used to fetch map data
  useEffect(() => {
    const map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/navigation-day-v1',
      center: [74.08041123938872,32.58447461740033],
      zoom: 11,
    })

    if(props.startCoordinates){
      addToMap(map, props.startCoordinates)

    }
    if(props.endCoordinates){
      addToMap(map, props.endCoordinates)
    }

    if(props.startCoordinates && props.endCoordinates){
      map.fitBounds([  
        props.startCoordinates,
        props.endCoordinates
        
      ], {
        padding: 60
      })
    }
  }, [props.startCoordinates, props.endCoordinates])

  const addToMap =(map, coordinates) => {
    const marker1 = new mapboxgl.Marker()
    .setLngLat(coordinates)
    .addTo(map);
    }

  return <Wrapper id='map'></Wrapper>
  }
  


export default Map

const Wrapper = tw.div`

  flex-1 h-1/2

`